/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function TestRobot(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('src/assets/robot.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="defaultScene">
        <group scale={0.1} />
        <group position={[0, 2.7, -0.8]} rotation={[-3.1, 0, 0]} />
        <group>
          <group position={[0.1, 0, 0]} scale={[1, 1, 1.3]}>
            <group position={[-0.7, -4.8, 0]} scale={[1.4, 1.1, 1.7]}>
              <mesh
                name="mesh_0"
                castShadow
                receiveShadow
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
                position={[0.9, 0, 0]}>
                <mesh
                  name="mesh_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.mesh_1.geometry}
                  material={nodes.mesh_1.material}
                  position={[0, 1.3, 0]}
                  scale={[0.4, 0.4, 1.1]}>
                  <mesh
                    name="mesh_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_2.geometry}
                    material={nodes.mesh_2.material}
                    position={[0, -3.3, 0]}
                    scale={[2.5, 2.4, 0.9]}
                  />
                </mesh>
              </mesh>
            </group>
            <mesh
              name="mesh_3"
              castShadow
              receiveShadow
              geometry={nodes.mesh_3.geometry}
              material={nodes.mesh_3.material}
              position={[1.9, 0, 0]}
              scale={[1, 1, 1.2]}>
              <mesh
                name="mesh_4"
                castShadow
                receiveShadow
                geometry={nodes.mesh_4.geometry}
                material={nodes.mesh_4.material}
                position={[-0.3, -1, 0]}
                scale={[1, 1, 0.9]}>
                <mesh
                  name="mesh_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.mesh_5.geometry}
                  material={nodes.mesh_5.material}
                  position={[-1, -0.4, 0]}
                  rotation={[0, 0, -0.1]}
                  scale={[0.6, 0.7, 1.2]}>
                  <mesh
                    name="mesh_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_6.geometry}
                    material={nodes.mesh_6.material}
                    position={[1.7, -0.6, 0]}
                    rotation={[0, 0, 0.1]}
                    scale={[1.3, 1.5, 0.8]}>
                    <group position={[-2, 2, 0]} scale={[1.2, 1, 1]}>
                      <mesh
                        name="mesh_7"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_7.geometry}
                        material={nodes.mesh_7.material}
                        position={[2.6, -4.9, 0]}
                        scale={[1.1, 1.1, 1]}
                      />
                      <mesh
                        name="mesh_8"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_8.geometry}
                        material={nodes.mesh_8.material}
                        position={[1.8, -3.9, 0]}
                        scale={[0.9, 3.1, 1]}
                      />
                    </group>
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
            <group>
              <mesh
                name="mesh_9"
                castShadow
                receiveShadow
                geometry={nodes.mesh_9.geometry}
                material={nodes.mesh_9.material}
                position={[0.4, -1.4, 0]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[1.1, 2.5, 1.9]}
              />
              <mesh
                name="mesh_10"
                castShadow
                receiveShadow
                geometry={nodes.mesh_10.geometry}
                material={nodes.mesh_10.material}
                position={[0.5, 0.7, 0]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[1.5, 1.5, 1.9]}
              />
            </group>
          </group>
          <mesh
            name="mesh_11"
            castShadow
            receiveShadow
            geometry={nodes.mesh_11.geometry}
            material={nodes.mesh_11.material}
            position={[0.8, 0.8, 1.3]}
            scale={[0.7, 0.7, 0.2]}
          />
          <group>
            <mesh
              name="mesh_12"
              castShadow
              receiveShadow
              geometry={nodes.mesh_12.geometry}
              material={nodes.mesh_12.material}
              position={[0, 3.9, 0.2]}
              scale={[0.5, 0.4, 1.4]}
            />
            <mesh
              name="mesh_13"
              castShadow
              receiveShadow
              geometry={nodes.mesh_13.geometry}
              material={nodes.mesh_13.material}
              position={[0, 2.6, 0]}
              scale={1.2}
            />
            <mesh
              name="mesh_14"
              castShadow
              receiveShadow
              geometry={nodes.mesh_14.geometry}
              material={nodes.mesh_14.material}
              position={[0, 2.6, 0.9]}
              scale={[0.8, 0.8, 0.5]}
            />
            <mesh
              name="mesh_15"
              castShadow
              receiveShadow
              geometry={nodes.mesh_15.geometry}
              material={nodes.mesh_15.material}
              position={[0, 0.3, 0.1]}
              scale={0.9}
            />
            <mesh
              name="mesh_16"
              castShadow
              receiveShadow
              geometry={nodes.mesh_16.geometry}
              material={nodes.mesh_16.material}
              position={[0, 3.3, 0.4]}
              scale={[2.2, 0.6, 1.4]}
            />
            <mesh
              name="mesh_17"
              castShadow
              receiveShadow
              geometry={nodes.mesh_17.geometry}
              material={nodes.mesh_17.material}
              position={[0, 1.9, -0.6]}
              scale={[2.6, 0.3, 1.1]}
            />
            <mesh
              name="mesh_18"
              castShadow
              receiveShadow
              geometry={nodes.mesh_18.geometry}
              material={nodes.mesh_18.material}
              position={[0, 2.1, -0.6]}
              scale={[2.7, 0.3, 1.1]}
            />
            <mesh
              name="mesh_19"
              castShadow
              receiveShadow
              geometry={nodes.mesh_19.geometry}
              material={nodes.mesh_19.material}
              position={[0, 2.6, 0.9]}
              scale={[1, 1, 0.6]}
            />
          </group>
          <group>
            <mesh
              name="mesh_20"
              castShadow
              receiveShadow
              geometry={nodes.mesh_20.geometry}
              material={nodes.mesh_20.material}
              position={[0, -0.1, -1.7]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.4, 1.3, 0.4]}
            />
            <mesh
              name="mesh_21"
              castShadow
              receiveShadow
              geometry={nodes.mesh_21.geometry}
              material={nodes.mesh_21.material}
              position={[0, 0.7, -1.8]}
              scale={[2.6, 2.6, 1.3]}
            />
          </group>
          <group position={[-0.1, 0, 0]} scale={[-1, 1, 1.3]}>
            <group position={[-0.7, -4.8, 0]} scale={[1.4, 1.1, 1.7]}>
              <mesh
                name="mesh_22"
                castShadow
                receiveShadow
                geometry={nodes.mesh_22.geometry}
                material={nodes.mesh_22.material}
                position={[0.9, 0, 0]}>
                <mesh
                  name="mesh_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.mesh_23.geometry}
                  material={nodes.mesh_23.material}
                  position={[0, 1.3, 0]}
                  scale={[0.4, 0.4, 1.1]}>
                  <mesh
                    name="mesh_24"
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_24.geometry}
                    material={nodes.mesh_24.material}
                    position={[0, -3.3, 0]}
                    scale={[2.5, 2.4, 0.9]}
                  />
                </mesh>
              </mesh>
            </group>
            <mesh
              name="mesh_25"
              castShadow
              receiveShadow
              geometry={nodes.mesh_25.geometry}
              material={nodes.mesh_25.material}
              position={[1.9, 0, 0]}
              scale={[1, 1, 1.2]}>
              <mesh
                name="mesh_26"
                castShadow
                receiveShadow
                geometry={nodes.mesh_26.geometry}
                material={nodes.mesh_26.material}
                position={[-0.3, -1, 0]}
                scale={[1, 1, 0.9]}>
                <mesh
                  name="mesh_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.mesh_27.geometry}
                  material={nodes.mesh_27.material}
                  position={[-1, -0.4, 0]}
                  rotation={[0, 0, -0.1]}
                  scale={[0.6, 0.7, 1.2]}>
                  <mesh
                    name="mesh_28"
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_28.geometry}
                    material={nodes.mesh_28.material}
                    position={[1.7, -0.6, 0]}
                    rotation={[0, 0, 0.1]}
                    scale={[1.3, 1.5, 0.8]}>
                    <group position={[-2, 2, 0]} scale={[1.2, 1, 1]}>
                      <mesh
                        name="mesh_29"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_29.geometry}
                        material={nodes.mesh_29.material}
                        position={[2.6, -4.9, 0]}
                        scale={[1.1, 1.1, 1]}
                      />
                      <mesh
                        name="mesh_30"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_30.geometry}
                        material={nodes.mesh_30.material}
                        position={[1.8, -3.9, 0]}
                        scale={[0.9, 3.1, 1]}
                      />
                    </group>
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
            <group>
              <mesh
                name="mesh_31"
                castShadow
                receiveShadow
                geometry={nodes.mesh_31.geometry}
                material={nodes.mesh_31.material}
                position={[0.4, -1.4, 0]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[1.1, 2.5, 1.9]}
              />
              <mesh
                name="mesh_32"
                castShadow
                receiveShadow
                geometry={nodes.mesh_32.geometry}
                material={nodes.mesh_32.material}
                position={[0.5, 0.7, 0]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[1.5, 1.5, 1.9]}
              />
            </group>
          </group>
          <group>
            <group>
              <mesh
                name="mesh_33"
                castShadow
                receiveShadow
                geometry={nodes.mesh_33.geometry}
                material={nodes.mesh_33.material}
                position={[0.3, 2.6, 1.2]}
                scale={[0.1, 0.3, 0.1]}
              />
              <mesh
                name="mesh_34"
                castShadow
                receiveShadow
                geometry={nodes.mesh_34.geometry}
                material={nodes.mesh_34.material}
                position={[-0.3, 2.6, 1.2]}
                scale={[0.1, 0.3, 0.1]}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('src/assets/robot.glb')
